### ISSUE TITLE
Error: can't find variable Buffer

### ISSUE THREAD

**Issue by tungleanh0902** [ton-org/ton-core#53]
I'm using ton/core lib for my telegram mini app. It works well when I ran on web but I have this error "can't find variable Buffer" when I ran on telegram mini app.
I'm using "@ton/core": "^0.59.0" and pnpm to install it.
Please help me

**Comment by nikkakiffar** [comment]
Hello, @tungleanh0902! Could you share some solution of this issue. I have the same problem.
